---
- name: install and configure all cli apps
  hosts: localhost
  
  tasks:
    - name: install and config vim
      include: vim.yml
      vars:
        vim_dir: "{{ ansible_env.HOME }}/.vim"
        vimrc: "{{ ansible_env.HOME }}/.vimrc"
    - name: install and configure bash
      include: bash.yml
      vars:
        bashrc: "{{ ansible_env.HOME }}/.bashrc"
        bash_aliases: "{{ ansible_env.HOME }}/.bash_aliases"        
