---
- name: install and configure all cli apps
  hosts: localhost
  
  tasks:
    - name: install packages
      include: tasks/other.yml
    - name: install and config vim
      include: tasks/vim.yml
      vars:
        vim_dir: "{{ ansible_env.HOME }}/.vim"
        vimrc: "{{ ansible_env.HOME }}/.vimrc"
    - name: install and configure bash
      tags: bash
      include: tasks/bash.yml
      vars:
        bashrc: "{{ ansible_env.HOME }}/.bashrc"
        bash_aliases: "{{ ansible_env.HOME }}/.bash_aliases"
        bash_functions: "{{ ansible_env.HOME }}/.bash_functions"        
    - name: install and configure fish
      tags: fish
      include: tasks/fish.yml
      vars:
        fish_aliases: "{{ ansible_env.HOME }}/.config/fish/conf.d/aliases.fish" 
        fish_functions: "{{ ansible_env.HOME }}/.config/fish/conf.d/functions.fish"        
