---
- name: BASH - Install required packages
  package:
    name:
      - bash
      - bash-completion
    state: latest
  become: yes

- name: BASH - copy over bashrc files
  copy:
    src: bashrc
    dest: "{{ bashrc }}"
    backup: yes
    mode: 0770

- name: BASH - copy over bash_aliases for ubuntu
  copy:
    src: aliases_ubuntu
    dest: "{{ bash_aliases }}"
    backup: yes
    mode: 0770
  when: ansible_distribution == "Ubuntu"
  tags:
    - copy_files

- name: BASH - copy over bash_aliases for ubuntu
  copy:
    src: aliases_fedora
    dest: "{{ bash_aliases }}"
    backup: yes
    mode: 0770
  when: ansible_distribution == "Fedora"
  tags:
    - copy_files

