---
- name: install cli packages
  package:
    name:
      - neofetch
      - micro
      - nano
      - ranger
      - git
      - tldr
      - zoxide
      - exa
      - ripgrep
      - bat
      - fzf
      - du-dust
      - ncdu
      - htop
      - bottom
      - tealdeer
      - fd
      - procs
      - duf
      - dua-cli
    state: latest
  become: yes
