  - name: VIM - Install required packages
    package:
      name:
        - vim
        - git
        - fzf
      state: latest
    become: yes

  - name: VIM - Install required packages (ubuntu)
    package:
      name:
        - fonts-powerline
      state: latest
    become: yes
    when: ansible_distribution == "Ubuntu"

  - name: VIM - Install required packages (fedora)
    package:
      name:
        - powerline-fonts
      state: latest
    become: yes
    when: ansible_distribution == "Fedora"

  - name: VIM - Ensure .vim/{autoload,bundle} directory exists
    file:
      path: "{{ item }}"
      state: directory
      recurse: no
      mode: 0750
    loop:
      - "{{ vim_dir }}"
      - "{{ vim_dir }}/autoload"
      - "{{ vim_dir }}/bundle"

  - name: VIM - Ensure Pathogen is in place
    get_url:
      dest: "{{ vim_dir }}/autoload/pathogen.vim"
      url: https://tpo.pe/pathogen.vim

  - name: VIM - Deploy plugins
    git:
      dest: "{{ vim_dir }}/bundle/{{ item.name }}"
      repo: "{{ item.url }}"
      clone: yes
      update: yes
      recursive: no
    loop:
    - name: vim-airline
      url: https://github.com/vim-airline/vim-airline
    - name: nerdtree
      url: https://github.com/preservim/nerdtree
    - name: fzf-vim
      url: https://github.com/junegunn/fzf.vim
    - name: vim-gitgutter
      url: https://github.com/airblade/vim-gitgutter
    - name: vim-fugitive
      url: https://github.com/tpope/vim-fugitive
    - name: vim-floaterm
      url: https://github.com/voldikss/vim-floaterm
    - name: dracula 
      url: https://github.com/dracula/vim

  - name: VIM - Ensure .vimrc config in place
    copy:
      src: vimrc
      dest: "{{ vimrc }}"
      backup: yes
      mode: 0770
