execute pathogen#infect()
syntax on
filetype plugin indent on

colorscheme  dracula

" line numbers
set nu
set relativenumber
" tabs as spaces
set smartindent
set tabstop=4 softtabstop=4
set shiftwidth=4
set expandtab
" other custom vim settings
set noerrorbells
set nowrap
set nohlsearch
set hidden
set incsearch
set scrolloff=8

" Configuration vim Airline
set laststatus=2

let g:airline#extensions#tabline#enabled=1
let g:airline_powerline_fonts=1

" Configuration NERDTree
map <F5> :NERDTreeToggle<CR>

" Configuration floaterm
let g:floaterm_keymap_toggle = '<F12>'
let g:floaterm_width = 0.9
let g:floaterm_height = 0.9

" Configuration Vim.FZF
let g:fzf_preview_window = 'right:50%'
let g:fzf_layout = { 'window': { 'width': 0.9, 'height': 0.6  }  }
